backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/rentals" 
public_folder: "/assets/rentals"
collections:
  - name: "rentals"
    label: "Rentals"
    folder: "src/rentals"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Bedrooms", name: "bedrooms", widget: "string" }
      - { label: "Bathrooms", name: "bathrooms", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Square Feet", name: "squareFeet", widget: "string" }
      - { label: "Terrace", name: "terrace", widget: "string" }
      - { label: "Car Parking", name: "carParking", widget: "string" }
      - { label: "Floor", name: "floor", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Amenity 1", name: "amenities[0]", widget: "select", options: ["Covered parking", "Pet-friendly", "Swimming pool"] }
      - { label: "Amenity 2", name: "amenities[1]", widget: "select", options: ["Covered parking", "Pet-friendly", "Swimming pool"] }
      - { label: "Amenity 3", name: "amenities[2]", widget: "select", options: ["Covered parking", "Pet-friendly", "Swimming pool"] }