backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/rentals" 
public_folder: "/assets/rentals"
collections:
  - name: "rentals"
    label: "Rentals"
    folder: "src/rentals"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Bedrooms", name: "bedrooms", widget: "string" }
      - { label: "Bathrooms", name: "bathroom", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "SquareFeet", name: "squarefeet", widget: "string" }
      - { label: "Terrace", name: "terrace", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      